#!/bin/bash

LD_LIBRARY_PATH=/opt/kiddo/lib PYTHONPATH=/opt/kiddo/lib/python3/dist-packages QT_PLUGIN_PATH=/opt/kiddo/lib/plugins QML2_IMPORT_PATH=/opt/kiddo/lib/qml QT_QPA_FONTDIR=/opt/kiddo/lib/fonts python3.4 /opt/kiddo/bin/cura_app.py "$@"
